version: '3'
services:
  # app:
  #   image: leandrino/dashboard-report-graphql
  #   container_name: dashboard-report-graphql
  #   env_file:
  #     - .env
  #   ports:
  #     - 3000:3000
  #   links:
  #     - postgresDB

  postgresDB:
    image: postgres:10
    restart: always
    container_name: postgresDB 
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
